# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/converter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3 import types_pb2 as v3_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12v3/converter.proto\x12\x02v3\x1a\x0ev3/types.proto\"_\n\x18\x43onvertAggregatesRequest\x12 \n\x07\x63onvert\x18\x01 \x01(\x0b\x32\x0f.v3.ConvertArgs\x12!\n\naggregates\x18\x02 \x03(\x0b\x32\r.v3.Aggregate\">\n\x19\x43onvertAggregatesResponse\x12!\n\naggregates\x18\x01 \x03(\x0b\x32\r.v3.Aggregate\"_\n\x18\x43onvertDatapointsRequest\x12 \n\x07\x63onvert\x18\x01 \x01(\x0b\x32\x0f.v3.ConvertArgs\x12!\n\ndatapoints\x18\x02 \x03(\x0b\x32\r.v3.Datapoint\">\n\x19\x43onvertDatapointsResponse\x12!\n\ndatapoints\x18\x01 \x03(\x0b\x32\r.v3.Datapoint2\xba\x01\n\x10\x43onverterService\x12R\n\x11\x43onvertAggregates\x12\x1c.v3.ConvertAggregatesRequest\x1a\x1d.v3.ConvertAggregatesResponse\"\x00\x12R\n\x11\x43onvertDatapoints\x12\x1c.v3.ConvertDatapointsRequest\x1a\x1d.v3.ConvertDatapointsResponse\"\x00\x42\x38Z6github.com/dendrascience/dendra-data-api/release/go/v3b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.converter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/dendrascience/dendra-data-api/release/go/v3'
  _CONVERTAGGREGATESREQUEST._serialized_start=42
  _CONVERTAGGREGATESREQUEST._serialized_end=137
  _CONVERTAGGREGATESRESPONSE._serialized_start=139
  _CONVERTAGGREGATESRESPONSE._serialized_end=201
  _CONVERTDATAPOINTSREQUEST._serialized_start=203
  _CONVERTDATAPOINTSREQUEST._serialized_end=298
  _CONVERTDATAPOINTSRESPONSE._serialized_start=300
  _CONVERTDATAPOINTSRESPONSE._serialized_end=362
  _CONVERTERSERVICE._serialized_start=365
  _CONVERTERSERVICE._serialized_end=551
# @@protoc_insertion_point(module_scope)
