# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v3 import converter_pb2 as v3_dot_converter__pb2


class ConverterServiceStub(object):
    """NOTES:
    rpc ListUnits
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertAggregates = channel.unary_unary(
                '/v3.ConverterService/ConvertAggregates',
                request_serializer=v3_dot_converter__pb2.ConvertAggregatesRequest.SerializeToString,
                response_deserializer=v3_dot_converter__pb2.ConvertAggregatesResponse.FromString,
                )
        self.ConvertDatapoints = channel.unary_unary(
                '/v3.ConverterService/ConvertDatapoints',
                request_serializer=v3_dot_converter__pb2.ConvertDatapointsRequest.SerializeToString,
                response_deserializer=v3_dot_converter__pb2.ConvertDatapointsResponse.FromString,
                )


class ConverterServiceServicer(object):
    """NOTES:
    rpc ListUnits
    """

    def ConvertAggregates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertDatapoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConverterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertAggregates': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertAggregates,
                    request_deserializer=v3_dot_converter__pb2.ConvertAggregatesRequest.FromString,
                    response_serializer=v3_dot_converter__pb2.ConvertAggregatesResponse.SerializeToString,
            ),
            'ConvertDatapoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertDatapoints,
                    request_deserializer=v3_dot_converter__pb2.ConvertDatapointsRequest.FromString,
                    response_serializer=v3_dot_converter__pb2.ConvertDatapointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v3.ConverterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConverterService(object):
    """NOTES:
    rpc ListUnits
    """

    @staticmethod
    def ConvertAggregates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v3.ConverterService/ConvertAggregates',
            v3_dot_converter__pb2.ConvertAggregatesRequest.SerializeToString,
            v3_dot_converter__pb2.ConvertAggregatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConvertDatapoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v3.ConverterService/ConvertDatapoints',
            v3_dot_converter__pb2.ConvertDatapointsRequest.SerializeToString,
            v3_dot_converter__pb2.ConvertDatapointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
