# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v3 import metadata_pb2 as v3_dot_metadata__pb2


class MetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDatastream = channel.unary_unary(
                '/v3.MetadataService/GetDatastream',
                request_serializer=v3_dot_metadata__pb2.GetDatastreamRequest.SerializeToString,
                response_deserializer=v3_dot_metadata__pb2.GetDatastreamResponse.FromString,
                )


class MetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDatastream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDatastream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatastream,
                    request_deserializer=v3_dot_metadata__pb2.GetDatastreamRequest.FromString,
                    response_serializer=v3_dot_metadata__pb2.GetDatastreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v3.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDatastream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v3.MetadataService/GetDatastream',
            v3_dot_metadata__pb2.GetDatastreamRequest.SerializeToString,
            v3_dot_metadata__pb2.GetDatastreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
