# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/transformer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v3 import types_pb2 as v3_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14v3/transformer.proto\x12\x02v3\x1a\x0ev3/types.proto\"_\n\x14TransformManyRequest\x12$\n\ttransform\x18\x01 \x01(\x0b\x32\x11.v3.TransformArgs\x12!\n\ndatapoints\x18\x02 \x03(\x0b\x32\r.v3.Datapoint\":\n\x15TransformManyResponse\x12!\n\ndatapoints\x18\x01 \x03(\x0b\x32\r.v3.Datapoint2\\\n\x12TransformerService\x12\x46\n\rTransformMany\x12\x18.v3.TransformManyRequest\x1a\x19.v3.TransformManyResponse\"\x00\x42\x38Z6github.com/dendrascience/dendra-data-api/release/go/v3b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.transformer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/dendrascience/dendra-data-api/release/go/v3'
  _TRANSFORMMANYREQUEST._serialized_start=44
  _TRANSFORMMANYREQUEST._serialized_end=139
  _TRANSFORMMANYRESPONSE._serialized_start=141
  _TRANSFORMMANYRESPONSE._serialized_end=199
  _TRANSFORMERSERVICE._serialized_start=201
  _TRANSFORMERSERVICE._serialized_end=293
# @@protoc_insertion_point(module_scope)
