# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from v3 import transformer_pb2 as v3_dot_transformer__pb2


class TransformerServiceStub(object):
    """NOTES:
    rpc TransformOne
    rpc TransformStream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransformMany = channel.unary_unary(
                '/v3.TransformerService/TransformMany',
                request_serializer=v3_dot_transformer__pb2.TransformManyRequest.SerializeToString,
                response_deserializer=v3_dot_transformer__pb2.TransformManyResponse.FromString,
                )


class TransformerServiceServicer(object):
    """NOTES:
    rpc TransformOne
    rpc TransformStream
    """

    def TransformMany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransformerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransformMany': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformMany,
                    request_deserializer=v3_dot_transformer__pb2.TransformManyRequest.FromString,
                    response_serializer=v3_dot_transformer__pb2.TransformManyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v3.TransformerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransformerService(object):
    """NOTES:
    rpc TransformOne
    rpc TransformStream
    """

    @staticmethod
    def TransformMany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v3.TransformerService/TransformMany',
            v3_dot_transformer__pb2.TransformManyRequest.SerializeToString,
            v3_dot_transformer__pb2.TransformManyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
