// source: v3/metadata.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var v3_types_pb = require('../v3/types_pb.js');
goog.object.extend(proto, v3_types_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.v3.GetDatastreamRequest', null, global);
goog.exportSymbol('proto.v3.GetDatastreamResponse', null, global);
goog.exportSymbol('proto.v3.ListUomsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.GetDatastreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v3.GetDatastreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.GetDatastreamRequest.displayName = 'proto.v3.GetDatastreamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.GetDatastreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v3.GetDatastreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.GetDatastreamResponse.displayName = 'proto.v3.GetDatastreamResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.ListUomsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.ListUomsResponse.repeatedFields_, null);
};
goog.inherits(proto.v3.ListUomsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.ListUomsResponse.displayName = 'proto.v3.ListUomsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.GetDatastreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.GetDatastreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.GetDatastreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.GetDatastreamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    datastreamId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.GetDatastreamRequest}
 */
proto.v3.GetDatastreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.GetDatastreamRequest;
  return proto.v3.GetDatastreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.GetDatastreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.GetDatastreamRequest}
 */
proto.v3.GetDatastreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatastreamId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.GetDatastreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.GetDatastreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.GetDatastreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.GetDatastreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatastreamId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string datastream_id = 1;
 * @return {string}
 */
proto.v3.GetDatastreamRequest.prototype.getDatastreamId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.GetDatastreamRequest} returns this
 */
proto.v3.GetDatastreamRequest.prototype.setDatastreamId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.GetDatastreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.GetDatastreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.GetDatastreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.GetDatastreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    datastream: (f = msg.getDatastream()) && v3_types_pb.Datastream.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.GetDatastreamResponse}
 */
proto.v3.GetDatastreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.GetDatastreamResponse;
  return proto.v3.GetDatastreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.GetDatastreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.GetDatastreamResponse}
 */
proto.v3.GetDatastreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v3_types_pb.Datastream;
      reader.readMessage(value,v3_types_pb.Datastream.deserializeBinaryFromReader);
      msg.setDatastream(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.GetDatastreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.GetDatastreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.GetDatastreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.GetDatastreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatastream();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v3_types_pb.Datastream.serializeBinaryToWriter
    );
  }
};


/**
 * optional Datastream datastream = 1;
 * @return {?proto.v3.Datastream}
 */
proto.v3.GetDatastreamResponse.prototype.getDatastream = function() {
  return /** @type{?proto.v3.Datastream} */ (
    jspb.Message.getWrapperField(this, v3_types_pb.Datastream, 1));
};


/**
 * @param {?proto.v3.Datastream|undefined} value
 * @return {!proto.v3.GetDatastreamResponse} returns this
*/
proto.v3.GetDatastreamResponse.prototype.setDatastream = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.GetDatastreamResponse} returns this
 */
proto.v3.GetDatastreamResponse.prototype.clearDatastream = function() {
  return this.setDatastream(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.GetDatastreamResponse.prototype.hasDatastream = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.ListUomsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.ListUomsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.ListUomsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.ListUomsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.ListUomsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    uomsList: jspb.Message.toObjectList(msg.getUomsList(),
    v3_types_pb.Uom.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.ListUomsResponse}
 */
proto.v3.ListUomsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.ListUomsResponse;
  return proto.v3.ListUomsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.ListUomsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.ListUomsResponse}
 */
proto.v3.ListUomsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v3_types_pb.Uom;
      reader.readMessage(value,v3_types_pb.Uom.deserializeBinaryFromReader);
      msg.addUoms(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.ListUomsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.ListUomsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.ListUomsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.ListUomsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUomsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      v3_types_pb.Uom.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Uom uoms = 1;
 * @return {!Array<!proto.v3.Uom>}
 */
proto.v3.ListUomsResponse.prototype.getUomsList = function() {
  return /** @type{!Array<!proto.v3.Uom>} */ (
    jspb.Message.getRepeatedWrapperField(this, v3_types_pb.Uom, 1));
};


/**
 * @param {!Array<!proto.v3.Uom>} value
 * @return {!proto.v3.ListUomsResponse} returns this
*/
proto.v3.ListUomsResponse.prototype.setUomsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.v3.Uom=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v3.Uom}
 */
proto.v3.ListUomsResponse.prototype.addUoms = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.v3.Uom, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.ListUomsResponse} returns this
 */
proto.v3.ListUomsResponse.prototype.clearUomsList = function() {
  return this.setUomsList([]);
};


goog.object.extend(exports, proto.v3);
