// source: v3/provider.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var v3_types_pb = require('../v3/types_pb.js');
goog.object.extend(proto, v3_types_pb);
goog.exportSymbol('proto.v3.StreamDatapointsRequest', null, global);
goog.exportSymbol('proto.v3.StreamDatapointsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.StreamDatapointsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v3.StreamDatapointsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.StreamDatapointsRequest.displayName = 'proto.v3.StreamDatapointsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.StreamDatapointsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.StreamDatapointsResponse.repeatedFields_, null);
};
goog.inherits(proto.v3.StreamDatapointsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.StreamDatapointsResponse.displayName = 'proto.v3.StreamDatapointsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.StreamDatapointsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.StreamDatapointsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.StreamDatapointsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.StreamDatapointsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    query: (f = msg.getQuery()) && v3_types_pb.DatapointsQuery.toObject(includeInstance, f),
    configInstance: (f = msg.getConfigInstance()) && v3_types_pb.DatapointsConfigInstance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.StreamDatapointsRequest}
 */
proto.v3.StreamDatapointsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.StreamDatapointsRequest;
  return proto.v3.StreamDatapointsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.StreamDatapointsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.StreamDatapointsRequest}
 */
proto.v3.StreamDatapointsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v3_types_pb.DatapointsQuery;
      reader.readMessage(value,v3_types_pb.DatapointsQuery.deserializeBinaryFromReader);
      msg.setQuery(value);
      break;
    case 2:
      var value = new v3_types_pb.DatapointsConfigInstance;
      reader.readMessage(value,v3_types_pb.DatapointsConfigInstance.deserializeBinaryFromReader);
      msg.setConfigInstance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.StreamDatapointsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.StreamDatapointsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.StreamDatapointsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.StreamDatapointsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      v3_types_pb.DatapointsQuery.serializeBinaryToWriter
    );
  }
  f = message.getConfigInstance();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      v3_types_pb.DatapointsConfigInstance.serializeBinaryToWriter
    );
  }
};


/**
 * optional DatapointsQuery query = 1;
 * @return {?proto.v3.DatapointsQuery}
 */
proto.v3.StreamDatapointsRequest.prototype.getQuery = function() {
  return /** @type{?proto.v3.DatapointsQuery} */ (
    jspb.Message.getWrapperField(this, v3_types_pb.DatapointsQuery, 1));
};


/**
 * @param {?proto.v3.DatapointsQuery|undefined} value
 * @return {!proto.v3.StreamDatapointsRequest} returns this
*/
proto.v3.StreamDatapointsRequest.prototype.setQuery = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.StreamDatapointsRequest} returns this
 */
proto.v3.StreamDatapointsRequest.prototype.clearQuery = function() {
  return this.setQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.StreamDatapointsRequest.prototype.hasQuery = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DatapointsConfigInstance config_instance = 2;
 * @return {?proto.v3.DatapointsConfigInstance}
 */
proto.v3.StreamDatapointsRequest.prototype.getConfigInstance = function() {
  return /** @type{?proto.v3.DatapointsConfigInstance} */ (
    jspb.Message.getWrapperField(this, v3_types_pb.DatapointsConfigInstance, 2));
};


/**
 * @param {?proto.v3.DatapointsConfigInstance|undefined} value
 * @return {!proto.v3.StreamDatapointsRequest} returns this
*/
proto.v3.StreamDatapointsRequest.prototype.setConfigInstance = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.StreamDatapointsRequest} returns this
 */
proto.v3.StreamDatapointsRequest.prototype.clearConfigInstance = function() {
  return this.setConfigInstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.StreamDatapointsRequest.prototype.hasConfigInstance = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.StreamDatapointsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.StreamDatapointsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.StreamDatapointsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.StreamDatapointsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.StreamDatapointsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    datapointsList: jspb.Message.toObjectList(msg.getDatapointsList(),
    v3_types_pb.Datapoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.StreamDatapointsResponse}
 */
proto.v3.StreamDatapointsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.StreamDatapointsResponse;
  return proto.v3.StreamDatapointsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.StreamDatapointsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.StreamDatapointsResponse}
 */
proto.v3.StreamDatapointsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new v3_types_pb.Datapoint;
      reader.readMessage(value,v3_types_pb.Datapoint.deserializeBinaryFromReader);
      msg.addDatapoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.StreamDatapointsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.StreamDatapointsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.StreamDatapointsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.StreamDatapointsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatapointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      v3_types_pb.Datapoint.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Datapoint datapoints = 1;
 * @return {!Array<!proto.v3.Datapoint>}
 */
proto.v3.StreamDatapointsResponse.prototype.getDatapointsList = function() {
  return /** @type{!Array<!proto.v3.Datapoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, v3_types_pb.Datapoint, 1));
};


/**
 * @param {!Array<!proto.v3.Datapoint>} value
 * @return {!proto.v3.StreamDatapointsResponse} returns this
*/
proto.v3.StreamDatapointsResponse.prototype.setDatapointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.v3.Datapoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v3.Datapoint}
 */
proto.v3.StreamDatapointsResponse.prototype.addDatapoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.v3.Datapoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.StreamDatapointsResponse} returns this
 */
proto.v3.StreamDatapointsResponse.prototype.clearDatapointsList = function() {
  return this.setDatapointsList([]);
};


goog.object.extend(exports, proto.v3);
