// source: v3/types.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.v3.AnnotationActions', null, global);
goog.exportSymbol('proto.v3.Datapoint', null, global);
goog.exportSymbol('proto.v3.DatapointsConfigInstance', null, global);
goog.exportSymbol('proto.v3.DatapointsQuery', null, global);
goog.exportSymbol('proto.v3.Datastream', null, global);
goog.exportSymbol('proto.v3.EndTime', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.EndTime = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v3.EndTime, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.EndTime.displayName = 'proto.v3.EndTime';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.Datapoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.Datapoint.repeatedFields_, null);
};
goog.inherits(proto.v3.Datapoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.Datapoint.displayName = 'proto.v3.Datapoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.AnnotationActions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.AnnotationActions.repeatedFields_, null);
};
goog.inherits(proto.v3.AnnotationActions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.AnnotationActions.displayName = 'proto.v3.AnnotationActions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.DatapointsConfigInstance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.DatapointsConfigInstance.repeatedFields_, null);
};
goog.inherits(proto.v3.DatapointsConfigInstance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.DatapointsConfigInstance.displayName = 'proto.v3.DatapointsConfigInstance';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.DatapointsQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.v3.DatapointsQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.DatapointsQuery.displayName = 'proto.v3.DatapointsQuery';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.v3.Datastream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.v3.Datastream.repeatedFields_, null);
};
goog.inherits(proto.v3.Datastream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.v3.Datastream.displayName = 'proto.v3.Datastream';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.EndTime.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.EndTime.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.EndTime} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.EndTime.toObject = function(includeInstance, msg) {
  var f, obj = {
    t: (f = msg.getT()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    o: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.EndTime}
 */
proto.v3.EndTime.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.EndTime;
  return proto.v3.EndTime.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.EndTime} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.EndTime}
 */
proto.v3.EndTime.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setT(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setO(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.EndTime.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.EndTime.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.EndTime} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.EndTime.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getT();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getO();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp t = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.EndTime.prototype.getT = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.EndTime} returns this
*/
proto.v3.EndTime.prototype.setT = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.EndTime} returns this
 */
proto.v3.EndTime.prototype.clearT = function() {
  return this.setT(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.EndTime.prototype.hasT = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sint32 o = 2;
 * @return {number}
 */
proto.v3.EndTime.prototype.getO = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.v3.EndTime} returns this
 */
proto.v3.EndTime.prototype.setO = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.Datapoint.repeatedFields_ = [5,7,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.Datapoint.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.Datapoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.Datapoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.Datapoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    t: (f = msg.getT()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    o: jspb.Message.getFieldWithDefault(msg, 2, 0),
    d: (f = msg.getD()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    daList: jspb.Message.toObjectList(msg.getDaList(),
    google_protobuf_struct_pb.Struct.toObject, includeInstance),
    v: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    vaList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 7)) == null ? undefined : f,
    uv: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    g: (f = msg.getG()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    gcList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 11)) == null ? undefined : f,
    q: (f = msg.getQ()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    ti: (f = msg.getTi()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    et: (f = msg.getEt()) && proto.v3.EndTime.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.Datapoint}
 */
proto.v3.Datapoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.Datapoint;
  return proto.v3.Datapoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.Datapoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.Datapoint}
 */
proto.v3.Datapoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setT(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setO(value);
      break;
    case 4:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setD(value);
      break;
    case 5:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.addDa(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setV(value);
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addVa(values[i]);
      }
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setUv(value);
      break;
    case 10:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setG(value);
      break;
    case 11:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addGc(values[i]);
      }
      break;
    case 12:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setQ(value);
      break;
    case 16:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setTi(value);
      break;
    case 17:
      var value = new proto.v3.EndTime;
      reader.readMessage(value,proto.v3.EndTime.deserializeBinaryFromReader);
      msg.setEt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.Datapoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.Datapoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.Datapoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.Datapoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getT();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getO();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getD();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getDaList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getVaList();
  if (f.length > 0) {
    writer.writePackedDouble(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getG();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getGcList();
  if (f.length > 0) {
    writer.writePackedDouble(
      11,
      f
    );
  }
  f = message.getQ();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getTi();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getEt();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.v3.EndTime.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp t = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.Datapoint.prototype.getT = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setT = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearT = function() {
  return this.setT(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasT = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional sint32 o = 2;
 * @return {number}
 */
proto.v3.Datapoint.prototype.getO = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.setO = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.protobuf.Struct d = 4;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.Datapoint.prototype.getD = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 4));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setD = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearD = function() {
  return this.setD(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasD = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated google.protobuf.Struct da = 5;
 * @return {!Array<!proto.google.protobuf.Struct>}
 */
proto.v3.Datapoint.prototype.getDaList = function() {
  return /** @type{!Array<!proto.google.protobuf.Struct>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_struct_pb.Struct, 5));
};


/**
 * @param {!Array<!proto.google.protobuf.Struct>} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setDaList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.protobuf.Struct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Struct}
 */
proto.v3.Datapoint.prototype.addDa = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.protobuf.Struct, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearDaList = function() {
  return this.setDaList([]);
};


/**
 * optional double v = 6;
 * @return {number}
 */
proto.v3.Datapoint.prototype.getV = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.setV = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearV = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasV = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated double va = 7;
 * @return {!Array<number>}
 */
proto.v3.Datapoint.prototype.getVaList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.setVaList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.addVa = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearVaList = function() {
  return this.setVaList([]);
};


/**
 * optional double uv = 8;
 * @return {number}
 */
proto.v3.Datapoint.prototype.getUv = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.setUv = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearUv = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasUv = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Struct g = 10;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.Datapoint.prototype.getG = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 10));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setG = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearG = function() {
  return this.setG(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasG = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated double gc = 11;
 * @return {!Array<number>}
 */
proto.v3.Datapoint.prototype.getGcList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 11));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.setGcList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.addGc = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearGcList = function() {
  return this.setGcList([]);
};


/**
 * optional google.protobuf.Struct q = 12;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.Datapoint.prototype.getQ = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 12));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setQ = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearQ = function() {
  return this.setQ(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasQ = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.Struct ti = 16;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.Datapoint.prototype.getTi = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 16));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setTi = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearTi = function() {
  return this.setTi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasTi = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional EndTime et = 17;
 * @return {?proto.v3.EndTime}
 */
proto.v3.Datapoint.prototype.getEt = function() {
  return /** @type{?proto.v3.EndTime} */ (
    jspb.Message.getWrapperField(this, proto.v3.EndTime, 17));
};


/**
 * @param {?proto.v3.EndTime|undefined} value
 * @return {!proto.v3.Datapoint} returns this
*/
proto.v3.Datapoint.prototype.setEt = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.Datapoint} returns this
 */
proto.v3.Datapoint.prototype.clearEt = function() {
  return this.setEt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.Datapoint.prototype.hasEt = function() {
  return jspb.Message.getField(this, 17) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.AnnotationActions.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.AnnotationActions.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.AnnotationActions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.AnnotationActions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.AnnotationActions.toObject = function(includeInstance, msg) {
  var f, obj = {
    attrib: (f = msg.getAttrib()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    evaluate: jspb.Message.getFieldWithDefault(msg, 2, ""),
    exclude: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    flagList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.AnnotationActions}
 */
proto.v3.AnnotationActions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.AnnotationActions;
  return proto.v3.AnnotationActions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.AnnotationActions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.AnnotationActions}
 */
proto.v3.AnnotationActions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setAttrib(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEvaluate(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExclude(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addFlag(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.AnnotationActions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.AnnotationActions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.AnnotationActions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.AnnotationActions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttrib();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getEvaluate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExclude();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getFlagList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional google.protobuf.Struct attrib = 1;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.AnnotationActions.prototype.getAttrib = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 1));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.AnnotationActions} returns this
*/
proto.v3.AnnotationActions.prototype.setAttrib = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.clearAttrib = function() {
  return this.setAttrib(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.AnnotationActions.prototype.hasAttrib = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string evaluate = 2;
 * @return {string}
 */
proto.v3.AnnotationActions.prototype.getEvaluate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.setEvaluate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool exclude = 3;
 * @return {boolean}
 */
proto.v3.AnnotationActions.prototype.getExclude = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.setExclude = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated string flag = 4;
 * @return {!Array<string>}
 */
proto.v3.AnnotationActions.prototype.getFlagList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.setFlagList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.addFlag = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.AnnotationActions} returns this
 */
proto.v3.AnnotationActions.prototype.clearFlagList = function() {
  return this.setFlagList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.DatapointsConfigInstance.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.DatapointsConfigInstance.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.DatapointsConfigInstance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.DatapointsConfigInstance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.DatapointsConfigInstance.toObject = function(includeInstance, msg) {
  var f, obj = {
    beginsAt: (f = msg.getBeginsAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endsBefore: (f = msg.getEndsBefore()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    params: (f = msg.getParams()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    connection: jspb.Message.getFieldWithDefault(msg, 4, ""),
    path: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ref: jspb.Message.getFieldWithDefault(msg, 6, 0),
    actions: (f = msg.getActions()) && proto.v3.AnnotationActions.toObject(includeInstance, f),
    annotationIdsList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.DatapointsConfigInstance}
 */
proto.v3.DatapointsConfigInstance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.DatapointsConfigInstance;
  return proto.v3.DatapointsConfigInstance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.DatapointsConfigInstance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.DatapointsConfigInstance}
 */
proto.v3.DatapointsConfigInstance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBeginsAt(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndsBefore(value);
      break;
    case 3:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setConnection(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRef(value);
      break;
    case 10:
      var value = new proto.v3.AnnotationActions;
      reader.readMessage(value,proto.v3.AnnotationActions.deserializeBinaryFromReader);
      msg.setActions(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addAnnotationIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.DatapointsConfigInstance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.DatapointsConfigInstance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.DatapointsConfigInstance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.DatapointsConfigInstance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBeginsAt();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndsBefore();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getConnection();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRef();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getActions();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.v3.AnnotationActions.serializeBinaryToWriter
    );
  }
  f = message.getAnnotationIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp begins_at = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.DatapointsConfigInstance.prototype.getBeginsAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
*/
proto.v3.DatapointsConfigInstance.prototype.setBeginsAt = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.clearBeginsAt = function() {
  return this.setBeginsAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsConfigInstance.prototype.hasBeginsAt = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp ends_before = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.DatapointsConfigInstance.prototype.getEndsBefore = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
*/
proto.v3.DatapointsConfigInstance.prototype.setEndsBefore = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.clearEndsBefore = function() {
  return this.setEndsBefore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsConfigInstance.prototype.hasEndsBefore = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Struct params = 3;
 * @return {?proto.google.protobuf.Struct}
 */
proto.v3.DatapointsConfigInstance.prototype.getParams = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 3));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
*/
proto.v3.DatapointsConfigInstance.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsConfigInstance.prototype.hasParams = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string connection = 4;
 * @return {string}
 */
proto.v3.DatapointsConfigInstance.prototype.getConnection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.setConnection = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string path = 5;
 * @return {string}
 */
proto.v3.DatapointsConfigInstance.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 ref = 6;
 * @return {number}
 */
proto.v3.DatapointsConfigInstance.prototype.getRef = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.setRef = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional AnnotationActions actions = 10;
 * @return {?proto.v3.AnnotationActions}
 */
proto.v3.DatapointsConfigInstance.prototype.getActions = function() {
  return /** @type{?proto.v3.AnnotationActions} */ (
    jspb.Message.getWrapperField(this, proto.v3.AnnotationActions, 10));
};


/**
 * @param {?proto.v3.AnnotationActions|undefined} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
*/
proto.v3.DatapointsConfigInstance.prototype.setActions = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.clearActions = function() {
  return this.setActions(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsConfigInstance.prototype.hasActions = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated string annotation_ids = 11;
 * @return {!Array<string>}
 */
proto.v3.DatapointsConfigInstance.prototype.getAnnotationIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.setAnnotationIdsList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.addAnnotationIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.DatapointsConfigInstance} returns this
 */
proto.v3.DatapointsConfigInstance.prototype.clearAnnotationIdsList = function() {
  return this.setAnnotationIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.DatapointsQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.DatapointsQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.DatapointsQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.DatapointsQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    sortAsc: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    limit: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ltTime: (f = msg.getLtTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    gtTime: (f = msg.getGtTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    ltEqual: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    gtEqual: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    lat: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    lon: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.DatapointsQuery}
 */
proto.v3.DatapointsQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.DatapointsQuery;
  return proto.v3.DatapointsQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.DatapointsQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.DatapointsQuery}
 */
proto.v3.DatapointsQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSortAsc(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLimit(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLtTime(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setGtTime(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLtEqual(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGtEqual(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLat(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLon(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.DatapointsQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.DatapointsQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.DatapointsQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.DatapointsQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSortAsc();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getLtTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getGtTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLtEqual();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getGtEqual();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeDouble(
      8,
      f
    );
  }
};


/**
 * optional bool sort_asc = 1;
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.getSortAsc = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setSortAsc = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional uint32 limit = 2;
 * @return {number}
 */
proto.v3.DatapointsQuery.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setLimit = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.clearLimit = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.hasLimit = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp lt_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.DatapointsQuery.prototype.getLtTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.DatapointsQuery} returns this
*/
proto.v3.DatapointsQuery.prototype.setLtTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.clearLtTime = function() {
  return this.setLtTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.hasLtTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp gt_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.v3.DatapointsQuery.prototype.getGtTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.v3.DatapointsQuery} returns this
*/
proto.v3.DatapointsQuery.prototype.setGtTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.clearGtTime = function() {
  return this.setGtTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.hasGtTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool lt_equal = 5;
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.getLtEqual = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setLtEqual = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool gt_equal = 6;
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.getGtEqual = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setGtEqual = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional double lat = 7;
 * @return {number}
 */
proto.v3.DatapointsQuery.prototype.getLat = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setLat = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.clearLat = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.hasLat = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional double lon = 8;
 * @return {number}
 */
proto.v3.DatapointsQuery.prototype.getLon = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.setLon = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.v3.DatapointsQuery} returns this
 */
proto.v3.DatapointsQuery.prototype.clearLon = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.v3.DatapointsQuery.prototype.hasLon = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.v3.Datastream.repeatedFields_ = [5,10,11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.v3.Datastream.prototype.toObject = function(opt_includeInstance) {
  return proto.v3.Datastream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.v3.Datastream} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.Datastream.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    versionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    derivationMethod: jspb.Message.getFieldWithDefault(msg, 4, ""),
    derivedFromDatastreamIdsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    datapointsConfigList: jspb.Message.toObjectList(msg.getDatapointsConfigList(),
    proto.v3.DatapointsConfigInstance.toObject, includeInstance),
    datapointsConfigBuiltList: jspb.Message.toObjectList(msg.getDatapointsConfigBuiltList(),
    proto.v3.DatapointsConfigInstance.toObject, includeInstance),
    datapointsConfigRefdList: jspb.Message.toObjectList(msg.getDatapointsConfigRefdList(),
    proto.v3.DatapointsConfigInstance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.v3.Datastream}
 */
proto.v3.Datastream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.v3.Datastream;
  return proto.v3.Datastream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.v3.Datastream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.v3.Datastream}
 */
proto.v3.Datastream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersionId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDerivationMethod(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addDerivedFromDatastreamIds(value);
      break;
    case 10:
      var value = new proto.v3.DatapointsConfigInstance;
      reader.readMessage(value,proto.v3.DatapointsConfigInstance.deserializeBinaryFromReader);
      msg.addDatapointsConfig(value);
      break;
    case 11:
      var value = new proto.v3.DatapointsConfigInstance;
      reader.readMessage(value,proto.v3.DatapointsConfigInstance.deserializeBinaryFromReader);
      msg.addDatapointsConfigBuilt(value);
      break;
    case 12:
      var value = new proto.v3.DatapointsConfigInstance;
      reader.readMessage(value,proto.v3.DatapointsConfigInstance.deserializeBinaryFromReader);
      msg.addDatapointsConfigRefd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.v3.Datastream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.v3.Datastream.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.v3.Datastream} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.v3.Datastream.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDerivationMethod();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDerivedFromDatastreamIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getDatapointsConfigList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.v3.DatapointsConfigInstance.serializeBinaryToWriter
    );
  }
  f = message.getDatapointsConfigBuiltList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.v3.DatapointsConfigInstance.serializeBinaryToWriter
    );
  }
  f = message.getDatapointsConfigRefdList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.v3.DatapointsConfigInstance.serializeBinaryToWriter
    );
  }
};


/**
 * optional string _id = 1;
 * @return {string}
 */
proto.v3.Datastream.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.v3.Datastream.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string version_id = 3;
 * @return {string}
 */
proto.v3.Datastream.prototype.getVersionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.setVersionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string derivation_method = 4;
 * @return {string}
 */
proto.v3.Datastream.prototype.getDerivationMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.setDerivationMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string derived_from_datastream_ids = 5;
 * @return {!Array<string>}
 */
proto.v3.Datastream.prototype.getDerivedFromDatastreamIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.setDerivedFromDatastreamIdsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.addDerivedFromDatastreamIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.clearDerivedFromDatastreamIdsList = function() {
  return this.setDerivedFromDatastreamIdsList([]);
};


/**
 * repeated DatapointsConfigInstance datapoints_config = 10;
 * @return {!Array<!proto.v3.DatapointsConfigInstance>}
 */
proto.v3.Datastream.prototype.getDatapointsConfigList = function() {
  return /** @type{!Array<!proto.v3.DatapointsConfigInstance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.v3.DatapointsConfigInstance, 10));
};


/**
 * @param {!Array<!proto.v3.DatapointsConfigInstance>} value
 * @return {!proto.v3.Datastream} returns this
*/
proto.v3.Datastream.prototype.setDatapointsConfigList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.v3.DatapointsConfigInstance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v3.DatapointsConfigInstance}
 */
proto.v3.Datastream.prototype.addDatapointsConfig = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.v3.DatapointsConfigInstance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.clearDatapointsConfigList = function() {
  return this.setDatapointsConfigList([]);
};


/**
 * repeated DatapointsConfigInstance datapoints_config_built = 11;
 * @return {!Array<!proto.v3.DatapointsConfigInstance>}
 */
proto.v3.Datastream.prototype.getDatapointsConfigBuiltList = function() {
  return /** @type{!Array<!proto.v3.DatapointsConfigInstance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.v3.DatapointsConfigInstance, 11));
};


/**
 * @param {!Array<!proto.v3.DatapointsConfigInstance>} value
 * @return {!proto.v3.Datastream} returns this
*/
proto.v3.Datastream.prototype.setDatapointsConfigBuiltList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.v3.DatapointsConfigInstance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v3.DatapointsConfigInstance}
 */
proto.v3.Datastream.prototype.addDatapointsConfigBuilt = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.v3.DatapointsConfigInstance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.clearDatapointsConfigBuiltList = function() {
  return this.setDatapointsConfigBuiltList([]);
};


/**
 * repeated DatapointsConfigInstance datapoints_config_refd = 12;
 * @return {!Array<!proto.v3.DatapointsConfigInstance>}
 */
proto.v3.Datastream.prototype.getDatapointsConfigRefdList = function() {
  return /** @type{!Array<!proto.v3.DatapointsConfigInstance>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.v3.DatapointsConfigInstance, 12));
};


/**
 * @param {!Array<!proto.v3.DatapointsConfigInstance>} value
 * @return {!proto.v3.Datastream} returns this
*/
proto.v3.Datastream.prototype.setDatapointsConfigRefdList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.v3.DatapointsConfigInstance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.v3.DatapointsConfigInstance}
 */
proto.v3.Datastream.prototype.addDatapointsConfigRefd = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.v3.DatapointsConfigInstance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.v3.Datastream} returns this
 */
proto.v3.Datastream.prototype.clearDatapointsConfigRefdList = function() {
  return this.setDatapointsConfigRefdList([]);
};


goog.object.extend(exports, proto.v3);
